Improved and shortened validation errors in config files
Details:

* The jsonschema.exceptions.ValidationError exception was so far used in our
  own error messages as str(exc) which resulted in page long listings of
  the offending element and the validating schema element, so that the
  information about the actual issue drowned in that long text.

  This was improved with multiple changes:

  - Changed the error message by no longer using str(exc) but only exc.message.

  - Changed the reference to the failing element by no longer just concatenating
    the items on the exc.absolute_path, but by constructing a string similar
    to a JSON path, and by special casing the root elements.

  - Increased the minimum version of the jsonschema package from 2.6.0 to
    3.2.0 which gets some improvements on exc.message (mostly by removing the
    lengthy text with a reasonable error message).

  - The new jsonschema version requires pyrsistent>=0.14.0 which does not
    yet have support for Python>=3.10. Increased the minimum version of
    pyrsistent to 0.17.3 on Python<=3.6 and 0.18.1 on Python>=3.7.

  The improved and shortened error format is like the following example:

    Error: Validation of HMC credentials file myconfig/hmccreds_t218d_m12d.yaml
    failed on element 'extra_labels[0]': 'name' is a required property

Signed-off-by: Andreas Maier <maiera@de.ibm.com>